name: noaa-coops-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - autoflake=1.3
  - black=19.3b0
  - flake8=3.7.9
  - isort=4.3.21
  - make=4.2.1
  - mypy=0.711
  - pip=20.1.1
  - pytest=5.3.0
  - python=3.7.3
  - numpy
  - pandas
  - requests
  - zeep
  - pytest>=4.0
  - pytest-cov
