name: noaa-coops-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - autoflake
  - black
  - bumpversion
  - flake8
  - isort
  - make
  - mypy
  - pip
  - pytest
  - python>=3.7
  - numpy
  - pandas>=1.1.3
  - requests
  - zeep
  - pytest
  - pytest-cov
