name: Publish Python Package to TestPyPI and PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      # Poetry installed via pip for simplicity, then install deps via poetry
      - name: Install Poetry & dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-interaction

      - name: Publish package to TestPyPI
        id: publish_test  # Used to check if the step succeeded or failed
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config pypi-token.testpypi $TEST_PYPI_TOKEN
          poetry publish --build --repository testpypi

      - name: Publish package to PyPI
        if: steps.publish_test.outcome == 'success'
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build --repository pypi
