name: CI Suite

on: pull_request

jobs:
  lint:
    name: Lint - (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      # Poetry installed via pip for simplicity, then install deps via poetry
      - name: Install Poetry & dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-interaction

      - name: Lint
        run: |
          poetry run make lint

  test:
    needs: lint
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python: ${{ matrix.python-version }}

      # Poetry installed via pip for simplicity, then install deps via poetry
      - name: Install Poetry & dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-interaction

      - name: Test
        run: |
          poetry run pytest
